### ISSUE TITLE
[Bug]:  Recipe Integration with jei

### ISSUE THREAD

**Issue by celsiusqc** [Fuzss/metalbundles#1]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.0

### Notes (Required)

Hard to integrate into a modpack if the user has no idea of the recipe since it isnt read by jei properly because its a custom recipe type

**Comment by Fuzss** [comment]
Yeah, that was my custom smithing recipe type being missed by JEI.

In Puzzles Lib v8.0.17 this is changed to a crafting recipe with the same inputs instead to resolve any issues with JEI.
