### ISSUE TITLE
[Bug]: Bundle Upgrading not working on Fabric

### ISSUE THREAD

**Issue by Partonetrain** [Fuzss/metalbundles#10]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.1

### Notes (Required)

Bundles are not accepted into the Smithing Table. (In this screenshot, the bundle is on my mouse)
![image](https://github.com/Fuzss/metalbundles/assets/19861808/c4cd7a04-9caa-48e9-83d3-df2987ff05a9)

**Comment by Fuzss** [comment]
It‘s a shapeless crafting recipe now. Need to update the mod page description.

**Comment by TobiasReindl** [comment]
@Fuzss Do not want to open a new issue because of my question, but will there be a 1.20.4 version in the future? :)
