### ISSUE TITLE
[Bug]: Unable to upgrade bundles

### ISSUE THREAD

**Issue by BizarreCrow** [Fuzss/metalbundles#11]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

v8.0.1

### Minimal Setup (Required)

Yes

### Notes (Required)

You're unable to place the bundle in the smithing table, therefore you are unable to upgrade the bundle, I could be misunderstanding something, but mods that show all recipes also don't know what to do.

### latest.log (Required)

https://gist.github.com/BizarreCrow/ddf98e09ce47fef01bcdf4ea0d2e9de0

**Comment by Fuzss** [comment]
See #10.
