### ISSUE TITLE
[Bug]: No Config for Metal Bundles

### ISSUE THREAD

**Issue by BioMasterZap** [Fuzss/metalbundles#12]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

v20.4.0

### Minimal Setup (Required)

Yes

### Notes (Required)

Not positive this is unintended, but I am not seeing any config files for Metal Bundles. In a fresh profile, I get the server and client configs for iteminteractions and forgeconfigapiport (plus the fabric folder), but nothing for metalbundles itself.

While it does note not all mods will have config files, I did see a recent previous comment noting "Changing the capacity is now fully supported in 1.20.4" but I am not seeing any way to change this since it isn't in the configs listed above. If there is another way to do this that I am missing, please let me know. But given the information presented, it seems like it should be in a config file.

### latest.log (Required)

https://gist.github.com/BioMasterZap/07e0636b1f58a28c131eef5af42e89db

**Comment by Fuzss** [comment]
The bundles are fully controlled via data packs. The default files can be found here: https://github.com/Fuzss/metalbundles/tree/main/1.20.4/Common/src/generated/resources/data/metalbundles/item_container_providers

You can find some slightly outdated documentation [here](https://github.com/Fuzss/iteminteractions/blob/main/README.md). I'll write some proper documentation when I find the time.

**Comment by BioMasterZap** [comment]
Ah, well that is a bit disappointing. I might take a look into that later to see if it would still work for me. And I was just testing Easy Shulker Boxes and noticed it doesn't have configs either and see some mention about it on the data pack page. Is there a way to disable its tweaks to the Ender Chest? It is a pretty notable buff to have alongside some Shulker (and Vanilla Bundle) tweaks.

Also, a couple of slightly related things. First, is the Copper Bundle supposed to be a downgrade from the Leather Bundle by default? Copper is showing 128 capacity while Leather is 251, which feels like they might have been flipped. Also, I noticed that the metal bundles don't change their icon when they have contents like the vanilla bundle does, which would be nice even if not the most necessary due to the bar.

**Comment by BioMasterZap** [comment]
Np and thanks for the quick reply. And good to hear the ender chest thing is configurable. Guess I need to finally figure out how to work a data pack (they weren't a prevalent thing last time I did mod packs), but hopefully, it isn't as complex as it comes off.
