### ISSUE TITLE
[Bug]: Bundle inventory highlight doesn't exist when using the bedrockify mod

### ISSUE THREAD

**Issue by katienaa** [Fuzss/metalbundles#19]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

v20.4.4

### Minimal Setup (Required)

No

### Notes (Required)

- the inventory of the bundle doesn't highlight an item
![image](https://github.com/Fuzss/metalbundles/assets/147920085/9dac7022-f237-463e-9159-290c38fe7f2f)

- have the bedrockify mod (with the slot hover highlight option enabled) along with metal bundles, and hover over a bundle with items in it.
![image](https://github.com/Fuzss/metalbundles/assets/147920085/f4436267-5f90-48b4-9aa3-e34047ec179c)

- the expected behavior is for the slot highlight inside the bundle to not be invisible, otherwise it is difficult to use the bundle scrolling feature.

### latest.log (Required)

https://gist.github.com/katienaa/f1084f66da8bd38ac42bcb1271982be6

**Comment by Fuzss** [comment]
That's an issue on Bedrockify's end. I think there is a config option to disable their custom slot overlay which should resolve this for now.
