### ISSUE TITLE
1.19.2 support [Suggestion]: 

### ISSUE THREAD

**Issue by cerealconjugo** [Fuzss/metalbundles#2]
### Suggestion (Required)

i think 1.19.2 its a good candidate to get a backport, cause most mods are available there.

**Comment by cerealconjugo** [comment]
Forgive me if I bothered you, I didn't mean to. I wasn't asking for a Port or an specific release date. It was really a suggestion. I'm sorry

**Comment by Fuzss** [comment]
No worries! Just wanna keep the issue tracker clean so I can focus on actual bugs and crashes.
