### ISSUE TITLE
[Suggestion]: Allow configuring bundle capacity

### ISSUE THREAD

**Issue by CodeKartonka** [Fuzss/metalbundles#4]
### Suggestion (Required)

can u add please a config?
cant find one.

wanted to change this

{
  "type": "metalbundles:bundle",
  "background_color": "yellow",
  "capacity": 2304
}

but it not worked look like it hardcodet in ur class file ^^ 

    public static final int LEATHER_BUNDLE_CAPACITY = 64;
    public static final int COPPER_BUNDLE_CAPACITY = 128;
    public static final int IRON_BUNDLE_CAPACITY = 512;
    public static final int GOLDEN_BUNDLE_CAPACITY = 1024;
    public static final int DIAMOND_BUNDLE_CAPACITY = 2048;
    public static final int NETHERITE_BUNDLE_CAPACITY = 4096;
    private static final int BAR_COLOR = class_3532.method_15353(0.4F, 0.4F, 1.0F);
   
i tryed to add 1 row (9x64 stack) to leather and Copper 2row

thanks

**Comment by Fuzss** [comment]
Changing the capacity is now fully supported in 1.20.4. Won‘t do a backport though.
