### ISSUE TITLE
[Bug]: Bundles delete one another if right clicked on top of each other.

### ISSUE THREAD

**Issue by MysticCDIV** [Fuzss/metalbundles#5]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.0

### Notes (Required)

Playing on a server with friends and one tells me he lost his items. He told me how to recreate it and the bundle disappeared with items inside.
On to how to recreate.
Open inventory, left click a bundle with or without items in it, hover over any other bundle with or without items, bundle appears for a millisecond before disappearing with the items inside.
He expected the item to either not work and keep all of his items and bundles, but it was also accidental.

**Comment by Fuzss** [comment]
Fixed in v8.0.1.
